### ISSUE TITLE
AAAA fields (ipv6)

### ISSUE THREAD

**Issue by Etuldan** [aureooms/ovh-dns#5]
Hi,
It seems that AAAA records aren't supported.  Any plan to do it ?

**Comment by aureooms** [comment]
Hi! What have you tried and what is the error?

**Comment by aureooms** [comment]
Ah I see. The record type is hardcoded in `ovh-dns`. Have you tried to use [`ovh-api-client`](https://github.com/aureooms/ovh-api-client) directly? Can you try to use it and tell me if it works. Then a record type option could be added here if it makes sense.

**Comment by aureooms** [comment]
Fixed by #6 thanks to @dzenciarz!
